name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Format
      run: npm run format:check
    - name: Lint
      run: npm run lint:check
    - name: Test
      run: npm test
